apiVersion: v1
data:
  rabbitmq.conf: |
  {{- include "rabbitmq.conf" . | nindent 4}}
  advanced.config: |
  {{- include "advanced.config" . | nindent 4}}
  enabled_plugins: |
  {{- include "enabled_plugins" . | nindent 4}}
kind: ConfigMap
metadata:
  labels:
    {{- include "kpi-rabbitmq.labels" . | nindent 4 }}
  name: {{ .Values.global.name }}-configmap