{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kpi-rabbitmq.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.global.name }}
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
{{- end }}
